### PR TITLE
append: fix two errors in _append rules; one in avahi and one in systemd

### PR DESCRIPTION
**Pull request by tkatila**
Signed-off-by: Tuomas Katila <tuomas.katila@intel.com>

### CODE REVIEW

**Comment by pohly** [comment]
Thanks for fixing my bugs ;-}

The question just is: why was that not caught by testing earlier? Should we have and/or tests for these particular configure options?

**Comment by tkatila** [comment]
For both items there were warnings in the log.do_configure files, but the build didn't fail.

Refkit doesn't(?) have a component which would depend on the avahi's dns_sd.so. For systemd, I think by default "systemd-getty-generator" is enabled, so even though the the packageconfig was invalid, systemd was configured with getty-generator.

**Comment by ipuustin** [comment]
After small grepping (`git grep '_append.*=\ \"[^ \\]' meta-refkit-*`), we have

```
meta-refkit-computervision/recipes-image/images/refkit-image-computervision.bb:# REFKIT_IMAGE_COMPUTERVISION_EXTRA_INSTALL_append = "my-own-package"
meta-refkit-computervision/recipes-image/images/refkit-image-computervision.bb:# REFKIT_IMAGE_COMPUTERVISION_EXTRA_FEATURES_append = "dev-pkgs"
meta-refkit-core/classes/image-dsk.bbclass:INITRD_LIVE_append = "${@ ('${DEPLOY_DIR_IMAGE}/' + d.getVar('INITRD_IMAGE', expand=True) + '-${MACHINE}.cpio.gz') if d.getVar('INITRD_IMAGE', True) else ''}"
meta-refkit-core/classes/refkit-image.bbclass:APPEND_append = "${@ bb.utils.contains('IMAGE_FEATURES', 'dm-verity', ' dmverity=PARTUUID=${REFKIT_DM_VERITY_PARTUUID}', '', d) }"
meta-refkit-core/classes/refkit-image.bbclass:WICVARS_append = "${@ bb.utils.contains('IMAGE_FEATURES', 'dm-verity', ' \
meta-refkit-core/classes/refkit-image.bbclass:APPEND_append = "${@ ' init_fatal_sh' if (d.getVar('IMAGE_MODE') or '') == 'development' else ''}"
meta-refkit-core/classes/refkit-image.bbclass:APPEND_append = "${@bb.utils.contains('IMAGE_FEATURES', 'ima', ' rootflags=i_version', ' no-ima', d)}"
meta-refkit-core/classes/refkit-image.bbclass:APPEND_append = "${@bb.utils.contains('IMAGE_FEATURES', 'smack', '', ' security=none', d)}"
meta-refkit-core/classes/refkit-swupd-image.bbclass:IMAGE_INSTALL_append = "${@ ' efi-combo-trigger' if oe.types.boolean(d.getVar('REFKIT_USE_DSK_IMAGES') or '0') else '' }"
meta-refkit-core/classes/stateless.bbclass:ROOTFS_POSTUNINSTALL_COMMAND_append = "stateless_mangle_rootfs;"
meta-refkit-core/conf/distro/include/refkit-config.inc:PACKAGECONFIG_append_pn-systemd_refkit-config = "serial-getty-generator"
meta-refkit-core/recipes-connectivity/avahi/avahi_%.bbappend:EXTRA_OECONF_append_refkit-config = "--enable-compat-libdns_sd"
meta-refkit-core/recipes-connectivity/bluez5/bluez5_5%.bbappend:RRECOMMENDS_${PN}_append_refkit-config += "${PN}-client"
meta-refkit-core/recipes-images/images/refkit-image-common.bb:# REFKIT_IMAGE_COMMON_EXTRA_INSTALL_append = "my-own-package"
meta-refkit-core/recipes-images/images/refkit-image-common.bb:# REFKIT_IMAGE_COMMON_EXTRA_FEATURES_append = "dev-pkgs"
meta-refkit-gateway/recipes-image/images/refkit-image-gateway.bb:# REFKIT_IMAGE_GATEWAY_EXTRA_INSTALL_append = "my-own-package"
meta-refkit-gateway/recipes-image/images/refkit-image-gateway.bb:# REFKIT_IMAGE_GATEWAY_EXTRA_FEATURES_append = "dev-pkgs"
```

@tkatila, could you add to this PR also fixes to the other possible `_append` mistakes? At least `bluez5_5%.bbappend` looks like it has a real one. The comments should be fixed too.

**Comment by ipuustin** [comment]
Oh, I forgot `meta-refkit` itself from the grep command. It has one likely problem:

```
meta-refkit/lib/oeqa/selftest/refkit-poky.py:REFKIT_IMAGE_EXTRA_FEATURES_append = "empty-root-password"
```

**Comment by tkatila** [comment]
Sure, I can add those fixes as well.

**Comment by pohly** [comment]
On Mon, 2017-06-12 at 03:00 -0700, Ismo Puustinen wrote:
> meta-refkit-computervision/recipes-image/images/refkit-image-computervision.bb:# REFKIT_IMAGE_COMPUTERVISION_EXTRA_INSTALL_append = "my-own-package"
> meta-refkit-computervision/recipes-image/images/refkit-image-computervision.bb:# REFKIT_IMAGE_COMPUTERVISION_EXTRA_FEATURES_append = "dev-pkgs"

Worth fixing.

> meta-refkit-core/classes/image-dsk.bbclass:INITRD_LIVE_append = "${@ ('${DEPLOY_DIR_IMAGE}/' + d.getVar('INITRD_IMAGE', expand=True) + '-${MACHINE}.cpio.gz') if d.getVar('INITRD_IMAGE', True) else ''}"
> meta-refkit-core/classes/refkit-image.bbclass:APPEND_append = "${@ bb.utils.contains('IMAGE_FEATURES', 'dm-verity', ' dmverity=PARTUUID=${REFKIT_DM_VERITY_PARTUUID}', '', d) }"
> meta-refkit-core/classes/refkit-image.bbclass:WICVARS_append = "${@ bb.utils.contains('IMAGE_FEATURES', 'dm-verity', ' \
> meta-refkit-core/classes/refkit-image.bbclass:APPEND_append = "${@ ' init_fatal_sh' if (d.getVar('IMAGE_MODE') or '') == 'development' else ''}"
> meta-refkit-core/classes/refkit-image.bbclass:APPEND_append = "${@bb.utils.contains('IMAGE_FEATURES', 'ima', ' rootflags=i_version', ' no-ima', d)}"
> meta-refkit-core/classes/refkit-image.bbclass:APPEND_append = "${@bb.utils.contains('IMAGE_FEATURES', 'smack', '', ' security=none', d)}"
> meta-refkit-core/classes/refkit-swupd-image.bbclass:IMAGE_INSTALL_append = "${@ ' efi-combo-trigger' if oe.types.boolean(d.getVar('REFKIT_USE_DSK_IMAGES') or '0') else '' }"

Please don't change those unless the actual result lacks a leading
space. For example, INITRD_LIVE_append is broken (no leading space in
'${DEPLOY_DIR_IMAGE}/') but the APPEND_append are all fine (add nothing
when not needed, add leading space in front of word otherwise).

> meta-refkit-core/classes/stateless.bbclass:ROOTFS_POSTUNINSTALL_COMMAND_append = "stateless_mangle_rootfs;"

Not really wrong because ; is the separator, but leading space is more
consistent.

> meta-refkit-core/conf/distro/include/refkit-config.inc:PACKAGECONFIG_append_pn-systemd_refkit-config = "serial-getty-generator"

If systemd-getty-generator is enabled by default already, should we
really enable it explicitly again?

> meta-refkit-core/recipes-connectivity/avahi/avahi_%.bbappend:EXTRA_OECONF_append_refkit-config = "--enable-compat-libdns_sd"
> meta-refkit-core/recipes-connectivity/bluez5/bluez5_5%.bbappend:RRECOMMENDS_${PN}_append_refkit-config += "${PN}-client"
> meta-refkit-core/recipes-images/images/refkit-image-common.bb:# REFKIT_IMAGE_COMMON_EXTRA_INSTALL_append = "my-own-package"
> meta-refkit-core/recipes-images/images/refkit-image-common.bb:# REFKIT_IMAGE_COMMON_EXTRA_FEATURES_append = "dev-pkgs"
> meta-refkit-gateway/recipes-image/images/refkit-image-gateway.bb:# REFKIT_IMAGE_GATEWAY_EXTRA_INSTALL_append = "my-own-package"
> meta-refkit-gateway/recipes-image/images/refkit-image-gateway.bb:# REFKIT_IMAGE_GATEWAY_EXTRA_FEATURES_append = "dev-pkgs"

Should be fixed.

Note that _append += as in bluez5_5%.bbappend should be replaced with
_append plus leading space.

**Comment by mythi** [comment]
On Mon, Jun 12, 2017 at 1:45 PM, Patrick Ohly wrote:

> On Mon, 2017-06-12 at 03:00 -0700, Ismo Puustinen wrote:
>
>

> > meta-refkit-core/conf/distro/include/refkit-config.inc:
> PACKAGECONFIG_append_pn-systemd_refkit-config = "serial-getty-generator"
>
> If systemd-getty-generator is enabled by default already, should we
> really enable it explicitly again?
>

systemd-getty-generator is disabled by default.

**Comment by mythi** [comment]
@tkatila do you wish to keep this PR or #180 (they look about the same). FYI, you can make updates to an open PR by force pushing your local edits to the remote branch (e.g., here 'appendfixes')

**Comment by tkatila** [comment]
@mythi Let's keep this. The latest version should have all the fixes that were ok by reviewers.

**Comment by ipuustin** [comment]
The fixes look good to me now.

**Comment by mythi** [comment]
@tkatila please rebase

**Comment by tkatila** [comment]
"appendfixes" branch now contains a rebased version.

**Pull request merged**
