### PR TITLE
meta-intel-realsense layer update.

### PR DESCRIPTION
**Pull request by ipuustin**
Update meta-intel-realsense. Remove non-needed local patches. Add a simple validation test for the feature.

### CODE REVIEW

**Comment by ipuustin** [comment]
retest this please

**Comment by ipuustin** [comment]
retest this please

**Comment by ipuustin** [comment]
retest this please

**Comment by mythi** [comment]
For submodule updates we've added 'git submodule summary' in the commit message. Can you do that for 9572d47

**Comment by ipuustin** [comment]
All right, updated the commit message.

**Comment by mythi** [comment]
Thanks, Looks like it's not much after all. I'll need to figure out how to get the actual content shown for submodule updates in case of PR merges.

**Comment by ipuustin** [comment]
Rebased.

**Pull request merged**
