### PR TITLE
CI: add pre- and post-test results publish and reporting

### PR DESCRIPTION
**Pull request by okartau**
python3-unittest-xml-reporting and python-six packages are needed in Docker session
to make XML test-reports to be saved from post-tests.

In Jenkinsfile we will publish TEST-*.xml files produced in post-build stage.

Better git values handling: Create git ci_commit_id and commit list after check-out,
remove cross-layer-use of ci_git_commit

Signed-off-by: Olev Kartau <olev.kartau@intel.com>

### CODE REVIEW

**Comment by okartau** [comment]
test this please

**Comment by okartau** [comment]
strange, 2 times failed in post-build test with strange errors... something wrong with hosts?
test this please

**Comment by okartau** [comment]
test this please

**Comment by okartau** [comment]
I propose this is ready for merging, please review if you wish.
Example of tests summary report is near end of this log:
https://ostroproject.org/jenkins/job/intel-iot-refkit_pull-requests/1893/console

**Comment by okartau** [comment]
I forgot I should rebase to latest head, done now, so takes at least one more test run

**Comment by Arthil** [comment]
The GPIO pins were accidentally attached wrong way, when fixing a BBB problem (had to remove all the wires). It's fixed now. Test this please.

**Comment by okartau** [comment]
test this please

**Pull request merged**
