### PR TITLE
meta-iotqa: fixes and cleanup for test modules

### PR DESCRIPTION
**Pull request by ibarraJhumberto**
Fixes and cleanup for runtime test modules.

- Removed Soletta since it's not part of any refkit profile and is not tested
at this moment.

- Removed case_interface.py since it's only used by soletta tests that are being removed.

- Removed tags from modules, which aren't currently used.

- Added a fix to iotvt_wifi.py about incorrect paths.

- Added a fix to solve incorrect paths and typos in wifi_connect.py and extended_wifi_connect.py

- Added patches to improve naming and logic of iotivity module

- Added a base class for iotivity test modules

### CODE REVIEW

**Comment by ibarraJhumberto** [comment]
Rebased to master and added a new commit to remove unused tags

**Comment by skuusela** [comment]
```
SSH log file: /root/workspace/workspace/intel-iot-refkit_pull-requests_7/iottest/ssh_target_log.20000303080319
Traceback (most recent call last):
  File "iottest/runtest.py", line 256, in <module>
    ret = main()
  File "iottest/runtest.py", line 250, in main
    runner.loadTests()
  File "iottest/runtest.py", line 103, in loadTests
    super(RuntestTestContext, self).loadTests()
  File "/root/workspace/workspace/intel-iot-refkit_pull-requests_7/iottest/oeqa/oetest.py", line 298, in loadTests
    suites = [testloader.loadTestsFromName(name) for name in self.testslist]
  File "/root/workspace/workspace/intel-iot-refkit_pull-requests_7/iottest/oeqa/oetest.py", line 298, in <listcomp>
    suites = [testloader.loadTestsFromName(name) for name in self.testslist]
  File "/usr/lib/python3.4/unittest/loader.py", line 114, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'iotivity'
```

**Comment by ibarraJhumberto** [comment]
Fixed latest Commit, which had an unintended addition.

**Comment by mythi** [comment]
@ibarraJhumberto please rebase this

**Comment by ibarraJhumberto** [comment]
Rebased to master

**Pull request merged**
