### PR TITLE
meta-intel-realsense update

### PR DESCRIPTION
**Pull request by pohly**
This change is necessary to avoid build errors in PR #318 and PR #326
and probably everything else that triggers a rebuild of librealsense.

### CODE REVIEW

**Comment by mythi** [comment]
@pohly meta-intel-librealsense update did not help?

**Comment by pohly** [comment]
On Mon, 2017-11-27 at 10:21 +0000, Mikko Ylinen wrote:
> @pohly meta-intel-librealsense update did not help?

I thought we were stuck at the current version? Or is that some other
sub-component (meta-clang)?

Looking at the latest master, it looks like it did change the branch,
so updating should work. I'll use this PR to try that.

**Comment by ipuustin** [comment]
The `legacy` branch. :-)

**Comment by mythi** [comment]
@pohly thanks! I believe it's meta-clang you were thinking

@ipuustin looks like they've added librealsense2

**Pull request merged**
