### PR TITLE
pull in the latest changes

### PR DESCRIPTION
**Pull request by pohly**
Includes PR #268.

### CODE REVIEW

**Comment by okartau** [comment]
test this please, was fetch failure on builder

**Comment by pohly** [comment]
The fetch failure is deterministic. We need to use the proxy for https://downloadmirror.intel.com/26925/eng/microcode-${PV}.tgz but currently don't.

@okartau Can we be more specific in our no_proxy variable and drop the intel.com catchall?

**Comment by okartau** [comment]
test this please. one builder remains online with changed no_proxy

**Comment by pohly** [comment]
test this please

Build failed with a race condition in flatpak?

| /bin/sh: session-helper/flatpak-session-helper.service: No such file or directory
00:28:50.346 | Makefile:5308: recipe for target 'session-helper/flatpak-session-helper.service' failed
00:28:50.346 | make[2]: *** [session-helper/flatpak-session-helper.service] Error 1
00:28:50.346 | make[2]: *** Waiting for unfinished jobs....

**Comment by pohly** [comment]
@okartau the proxy change was successful, at least for the microcode download. However, as expected the build now fails because of https://bugzilla.yoctoproject.org/show_bug.cgi?id=11882, so we don't know whether other operations later on would fail because of the proxy change.

I propose to make the change everywhere and test it with other builds.

**Comment by mythi** [comment]
AFAICS this is now obsolete. https://bugzilla.yoctoproject.org/show_bug.cgi?id=11882 is fixed and I'm going to submit a new PR to update meta-intel (and some other submodules)

**Pull request closed without merging**
