### PR TITLE
Update oe-core and meta-oe.

### PR DESCRIPTION
**Pull request by ipuustin**
Trying to figure out BitBake issues in #113.

### CODE REVIEW

**Comment by mythi** [comment]
@ipuustin thanks

You might be missing this on our side:
```
> meta_oe_security_flags.inc: Disable PIE for libdevmapper
```

**Comment by mythi** [comment]
Looks like we don't need libdevmapper. Just the -native version.

**Comment by ipuustin** [comment]
Ok, this built fine. @mythi, do you need this PR or can I close this?

**Comment by mythi** [comment]
@ipuustin I took it since we need it for many reasons and it looked good. thanks!

**Pull request merged**
