### PR TITLE
test enhancements

### PR DESCRIPTION
**Pull request by pohly**
Nothing major, just the removal of mraa/upm/NodeJS from
refkit-image-common that Mikko proposed in PR #184 and another
enhancement that I found useful.

### CODE REVIEW

**Comment by pohly** [comment]
@ipuustin this is something we should be able to merge quickly, once testing is done.

**Comment by ipuustin** [comment]
Looks good to me. Let's merge this when the tests pass.

**Comment by ipuustin** [comment]
For some reason the `common` image mraa/upm tests didn't pass. ;-) Could you move them to use the `gateway` image?

**Comment by pohly** [comment]
On Tue, 2017-06-20 at 01:14 -0700, Ismo Puustinen wrote:
> For some reason the common image mraa/upm tests didn't pass. ;-) Could
> you move them to use the gateway image?

I don't know how that part of testing works. Someone else will have to
resolve this.

I had a quick look and I see that meta-iotqa/classes/test-iot.bbclass
apparently installs the failing binaries - to all images?! That wouldn't
make sense or would have to be changed, as it might pull in unwanted
content into refkit-image-common (although in this case, some shared
libraries end up as missing):

https://ostroproject.org/jenkins/job/intel-iot-refkit_pull-requests/1589/testReport/junit/qemu.refkit-image-common.oeqa.runtime.peripherals.upm.upm/UpmTest/test_upm_import/

/opt/upm-test/upm_test: error while loading shared libraries:
libupmc-utilities.so.1: cannot open shared object file: No such file or
directory

@mythi: as you suggested that mraa/upm/nodejs shouldn't be in
refkit-image-common, can you make sure that this gets worked on by QA or
someone?

**Comment by ipuustin** [comment]
@pohly Hey, I'm trying to fix your Refkit installer qemu tests now. ;-) The manifest files (such as `https://github.com/intel/intel-iot-refkit/blob/master/meta-iotqa/conf/test/refkit-image-common.manifest` for refkit-image-common) control which tests get run on which image. @Arthil will know more.

**Comment by Arthil** [comment]
@pohly Hey, like @ipuustin said, you can modify which tests are run in the manifest files located in https://github.com/intel/intel-iot-refkit/tree/master/meta-iotqa/conf/test . Also note that test in refkit-image-common.manifest are also run on computervision and gateway profiles. If you want to have these particular test only in gateway, you can remove them from refkit-image-common.manifest and add them to gateway instead.

**Comment by pohly** [comment]
On Tue, 2017-06-20 at 03:38 -0700, Christian da Costa wrote:
> @pohly Hey, like @ipuustin said, you can modify which tests are run in
> the manifest files located in
> https://github.com/intel/intel-iot-refkit/tree/master/meta-iotqa/conf/test . Also note that test in refkit-image-common.manifest are also run on computervision and gateway profiles. If you want to have these particular test only in gateway, you can remove them from refkit-image-common.manifest and add them to gateway instead.

That changes which tests get run.

But how do I prevent mraa-test from getting installed into
refkit-image-common? It doesn't belong there.

**Comment by ipuustin** [comment]
@pohly: try removing mraa-test from `IOTQA_TESTIMAGEDEPENDS`. In computer vision image, we have a separate package group for installing tests, examples, and benchmarks to test images (see https://github.com/intel/intel-iot-refkit/blob/master/meta-refkit-computervision/recipes-computervision/packagegroups/packagegroup-computervision-test.bb). Maybe installing mraa-test would need to be refactored into a similar package group for common image?

**Comment by pohly** [comment]
I'm not sure, but it looks like mraa-tests only gets installed during testing. So perhaps changing the manifests is really all that's needed. Let's see whether it passes now.

**Comment by pohly** [comment]
@mythi it passed testing now, so probably ready for merging.

**Pull request merged**
