### PR TITLE
[TEST_BUILD] build-project.sh: add computer vision with graphic support

### PR DESCRIPTION
**Pull request by YinThong**
Add graphic support on computer vision profile. Only target on meta-iotqa testing or DAFT testing purpose

Signed-off-by: Choong Yin Thong <yin.thong.choong@intel.com>

### CODE REVIEW

**Comment by YinThong** [comment]
test this please

**Comment by okartau** [comment]
ok to test

**Comment by YinThong** [comment]
test this please

**Comment by YinThong** [comment]
test this please

**Comment by YinThong** [comment]
test this please

**Pull request closed without merging**
