### PR TITLE
intel-iot-refkit: manually pull in updates

### PR DESCRIPTION
**Pull request by mythi**
* openembedded-core e02716c...d110937 (79):
  > nss: Fix nss-native so the checksum doesn't change with BUILD_ARCH
  > sstate: Make absolute symlinks an error
  > openssl/fontconfig/bzip2: Use relative symlinks instead of absolute ones (using a new class)
  > lib/oe/path: Add replace_absolute_symlinks function
  > gcc-cross-initial: Remove unneeded temporary sysroot
  > python3-native: Remove tests to save copying uneeded files around
  > glibc-package: Avoid race sstate races with do_stash_locale
  > oeqa/selftest/pkgdata: use m4 instead of bash
  > dosfstools: upgrade to 4.1
  > image_types.bbclass: fix image dependency chain collection
  > kernel-module-split: Allow custom suffix for package names
  > iproute2: Inherit pkgconfig
  > pcmciautils: Inherit pkgconfig
  > qemu: Add missing 'inherit pkgconfig'
  > latencytop: Add missing 'inherit pkgconfig'
  > pong-clock: Add missing 'inherit pkgconfig'
  > devtool: improve parse failure handling
  > recipetool: create: do not treat numbers in SCM URLs as versions
  > recipetool: create: properly handle npm optional dependencies
  > classes/npm: set HOME during do_install
  > classes/populate_sdk_ext: account for custom image tasks
  > classes/patch: switch to new bb.build.tasksbetween() function
  > classes/populate_sdk_ext: remove unnecessary dependencies breaking SDK_TARGETS
  > sanity.conf: Update minimum version requirement for devtool
  > staging: Add missing parameter to debug message
  > staging: Improve file creation resiliance
  > staging: Add shared manifest support
  > perl-native: Remove .packlist file
  > staging: Don't put ptest files into the sysroot
  > glibc: Separate locale files to their own sstate task
  > Revert "yocto-bsps: add 4.9 bbappend"
  > gcc-6: Sync gcc stddef.h with musl stddef.h
  > oeqa.buildperf: reword test descriptions
  > sdkext/cases oeqa/selftest: Updates decorators
  > bash: use update-alternatives for the bash binary
  > wic: fix call of serial_console_form_kargs
  > selftest: wic: stop using iso image type
  > selftest: wic: use wic-tools recipe to get STAGING_DIR
  > wic: isoimage-isohybrid: use wic-tools to get syslinux path
  > image_types_wic: remove dependency to do_bootimg
  > image: rename image-wic -> image_types_wic
  > libgpg-error_1.25.bb: Enable nativesdk
  > libgcrypt.inc: Add PACKAGECONFIG for 'capabilities'
  > wic: flatten imager class hierarchy
  > libgcrypt.inc: Enable nativesdk
  > oeqa/buildproject: Run gnu-configize by default
  > oeqa/runtime: Improve failure log output
  > gstreamer: update to 1.10.3
  > openssl: Updgrade 1.0.2j -> 1.0.2k
  > gdb 7.12: fix armv8b build
  > glib-2.0: native package should not depend on DISTRO_FEATURES
  > xserver-xorg: Fix X server 1.19 crash
  > yocto-bsps: add 4.9 bbappend
  > linux-yocto/4.9: yaffs2 fixes
  > kernel-yocto: log the BSP definition file
  > linux-yocto/4.9: update to -rt3
  > kernel-yocto/meta: common-pc: add pci-siov to feature fragments
  > linux-yocto/4.9: update to v4.9.6
  > ver_linux: Use /usr/bin/awk instead of /bin/awk
  > kernel-yocto: ecryptfs, NFC and CAN bus config updates
  > kern-tools: re-enable scc merge command
  > kernel-yocto/features: enable TPM
  > linux-yocto/4.9: update to 4.9.4
  > mesa: update to 13.0.4
  > qemu: Upgrade to 2.8.0
  > libtasn1: Upgrade 4.9 -> 4.10
  > ffmpeg: disable cpu autodetection
  > python-3-manifest: split out typing
  > python-3-manifest: add ipaddress to python3-io
  > python-3-manifest: add _compat_pickle to python3-pickle
  > python-3-manifest: add socketserver to netserver
  > python-3-manifest: add argparse to RDEPENDS for netclient
  > python3-manifest: move htlm.py to python3-html
  > python-3-manifest: fix adding imp to importlib
  > libbsd: libbsd-overlay.pc: Set Cflags to use -I instead of -isystem
  > libsolv: split libsolvext into it's own pkg-config
  > xserver-xorg: fix 16bit modes
  > pkgconfig: fix typo introduced during recent conversion to PACKAGECONFIG
  > eudev: add RPROVIDES so eudev-hwdb provides udev-hwdb

* bitbake 2a309cd...95deeca (4):
  > bitbake: Update version to 1.33.1
  > fetch2/npm: fix handling of os field
  > fetch2/npm: handle items only in optionalDependencies
  > lib/bb/build: add tasksbetween() function

Signed-off-by: Mikko Ylinen <mikko.ylinen@linux.intel.com>

### CODE REVIEW

**Comment by mythi** [comment]
test this please

**Comment by mythi** [comment]
test this please

**Comment by mythi** [comment]
test this please

**Comment by mythi** [comment]
test this please

**Comment by mythi** [comment]
test this please

**Comment by mythi** [comment]
test this please

**Comment by okartau** [comment]
test this please

**Comment by mythi** [comment]
test this please

**Comment by okartau** [comment]
test this please

**Comment by mythi** [comment]
test this please

**Pull request merged**
