### PR TITLE
[TEST_BUILD] meta-iotqa: add qa tests for mraa-gpio get  

### PR DESCRIPTION
**Pull request by AshwinSoman**
Made changes to validate  mraa-gpio get value

Signed-off-by: Ashwin Soman <ashwinx.soman@intel.com>

### CODE REVIEW

**Comment by AshwinSoman** [comment]
Please help to test this build.

**Comment by okartau** [comment]
ok to test

**Comment by mythi** [comment]
how is this related to #254?

**Comment by AshwinSoman** [comment]
This is sets BeagleBone direction to out and checks value at DUT another test case for  mraa-gpio 

I made separate branch so that failure of any one of these don't stop merging of other in master .

**Comment by AshwinSoman** [comment]
If you want I can merge #254 and #287

**Comment by mythi** [comment]
yes, please add the new tests in mraa_gpio

**Pull request closed without merging**
