### PR TITLE
Enable helloworld test for industrial profile

### PR DESCRIPTION
**Pull request by rojkov**
Fixes [YOCTO #11462]

Also removes the horrendous kludge disabling industrial profile.

### CODE REVIEW

**Comment by rojkov** [comment]
test this please

**Comment by rojkov** [comment]
test this please

**Comment by rojkov** [comment]
@ipuustin @klihub could you please review this and merge?

**Comment by ipuustin** [comment]
It might be cleaner to `git revert` the kludge patch. Then it would be clear that the kludge is completely removed.

**Comment by rojkov** [comment]
@Arthil I've just realized that the test case still doesn't run in CI? What else needs to be added to let oeqa discover `refkit-image-industrial.manifest`?

**Comment by Arthil** [comment]
@rojkov I will look into this.

**Comment by rojkov** [comment]
* reformatted the commit revert to use `git revert` (no patch content has changed);
* force pushed.

**Comment by ipuustin** [comment]
retest this please

**Comment by ipuustin** [comment]
retest this please

**Pull request merged**
