### PR TITLE
Add input group because systemd is anyway creating it.

### PR DESCRIPTION
**Pull request by juimonen**
Signed-off-by: Jaska Uimonen <jaska.uimonen@intel.com>

### CODE REVIEW

**Comment by mythi** [comment]
@juimonen if it's being created, why is this change needed?

**Comment by juimonen** [comment]
same as with audio group. it is created in first boot by systemd so you can add users to it in bitbaking.

**Comment by juimonen** [comment]
so you _can't_ add users in bitbake

**Comment by mythi** [comment]
@juimonen can you write that in the commit message?

**Comment by mythi** [comment]
Let's track this part of #145

**Pull request closed without merging**
