### PR TITLE
esdk: build and test eSDK installers

### PR DESCRIPTION
**Pull request by mythi**

### CODE REVIEW

**Comment by mythi** [comment]
test this please

**Comment by mythi** [comment]
test this please

**Comment by mythi** [comment]
@rojkov would 1f88660 look OK?

**Comment by rojkov** [comment]
@mythi Yes, that's OK. I should have limited this setting to target only from the beginning.

**Comment by mythi** [comment]
@pohly good catch. does this PR look good otherwise?

**Comment by okartau** [comment]
test this please

**Pull request merged**
