### PR TITLE
Include a list of added commits to master build email

### PR DESCRIPTION
**Pull request by skuusela**
The email should look something like:
```
Git commit hash: 6cd5c6bef696cfa18b87739f072b1f4023e12739

Added commits:

    Include 'common-test' features to all development profile images
    meta-iotqa: Clean up wifi connect test
    meta-iotqa: Enable wifi test
    meta-iotqa: Disable wifi test for Minnowboard Turbot

Test results:

Image: refkit-image-common-intel-corei7-64-2017-03-06_23-48-15-build-349.wic
  Device: 570x
  Total:24  Pass:24  Fail:0  Skip:0  Error:0
  Run rate:100%  Pass rate of total:100%  Pass rate of exec:100%
-------------------------------------------------------------------
Image: refkit-image-common-intel-corei7-64-2017-03-06_23-48-15-build-349.wic
  Device: minnowboardturbot
  Total:24  Pass:24  Fail:0  Skip:0  Error:0
  Run rate:100%  Pass rate of total:100%  Pass rate of exec:100%
-------------------------------------------------------------------
```

Signed-off-by: Simo Kuusela <simo.kuusela@intel.com>

### CODE REVIEW

**Comment by mythi** [comment]
If the git repo available, would this work:
```git rev-list HEAD^...HEAD --oneline --no-merges```

Similarly for ci_git_commit ```git rev-list```could be used

**Comment by skuusela** [comment]
@mythi Yes, your solution seems to work nicely. Much simpler and cleaner.

**Comment by mythi** [comment]
On Wed, Mar 8, 2017 at 11:22 AM, skuusela wrote:

> @mythi <https://github.com/mythi> Yes, your solution seems to work
> nicely. Much simpler and cleaner.
>
>
> It works as long as there are merge commits (and each new master is based
on a github
merge). It's probably good to add a note about that.

**Comment by skuusela** [comment]
@mythi Added a note to commit description and on the line the command is run on.

**Pull request merged**
