### PR TITLE
[Test] Build image without compressed variants

### PR DESCRIPTION
**Pull request by skuusela**
Signed-off-by: Simo Kuusela <simo.kuusela@intel.com>

### CODE REVIEW

**Comment by skuusela** [comment]
test this please

**Comment by skuusela** [comment]
test this please

**Comment by Arthil** [comment]
test this please

**Comment by skuusela** [comment]
test this please

**Comment by skuusela** [comment]
test this please

**Comment by skuusela** [comment]
This PR made building, storing and post-build test phase in Jenkins few minutes faster but for some reason made the last parallel test run phase few minutes slower. Few times when testing this PR there was this error when testing server was downloading the images:
```
Cannot contact refkit-tester-01: java.lang.InterruptedException
```
If the slowdown gets solved this PR would make CI run several minutes faster.

**Comment by skuusela** [comment]
I'm closing this PR as I won't be working on this anymore.

**Pull request closed without merging**
