### PR TITLE
meta-iotqa: add gstreamer commandline tests

### PR DESCRIPTION
**Pull request by epyeoh**
Retest gstreamer test case after rebase the branch.

### CODE REVIEW

**Comment by ipuustin** [comment]
The tests look good. You should not change your previous patches in the PR by patching them more: instead fix the patches locally using `git rebase -i` or `git commit --amend` and then force push them to your branch.

**Comment by epyeoh** [comment]
Ismo, thanks for your sharing on rebase. I will do that next time. 
Do you think this gstreamer tests are ready to be merged to master?

**Comment by ipuustin** [comment]
The tests look good, but you will still have to rebase and force push before merge. :-) Something like this might do the trick (adapt the commands to your setup):

    git fetch origin
    git rebase -i origin/master
           <use "s" and "f" to squash all your commits into one or two commits>
    git push https://github.com/epyeoh/intel-iot-refkit.git HEAD:gstreamer --force

**Comment by ipuustin** [comment]
The commits are good now.

**Comment by mythi** [comment]
+1 too

**Comment by mythi** [comment]
test this please

**Comment by epyeoh** [comment]
test this please

**Comment by mythi** [comment]
test this please 

looks like a Jenkins glitch

**Comment by epyeoh** [comment]
test this please

**Comment by mythi** [comment]
@epyeoh could you rebase the PR too, thanks!

**Comment by epyeoh** [comment]
@mythi done rebase

**Pull request merged**
