### PR TITLE
CI: update exclude set, publish and test multiple configs, "headless" main config

### PR DESCRIPTION
**Pull request by pohly**
This extends PR #264.

### CODE REVIEW

**Comment by okartau** [comment]
now this fails on tester images fetch, because I added path glibc/ in few places which latest commit
turned into headless-glibc. Either you need to change those places in this PR, or I pick 4th commit from here into my original PR and continue there

**Comment by okartau** [comment]
do_testsdkext still thinks DEPLOY_DIR is tmp-glibc/deploy ?

**Comment by pohly** [comment]
Hrrm, must be hard-coded somewhere.

**Comment by pohly** [comment]
@okartau Now all code and test seems to be happy with tmp-headless/x11/wayland-glibc. Shall we merge it?

**Comment by okartau** [comment]
yes, looks good. One of my changes left indents in not-so-clean state where I turned piece of code into a function in publisher. My plan was to keep the indents for better diff readability in that commit, then fix indents in separate commit. but thats cosmetic issue and can be changed later. Lets move forward and merge this.

**Pull request merged**
