### PR TITLE
enable usrmerge

### PR DESCRIPTION
**Pull request by avalluri**
Just a test build to test usrmerge oe-core chagnes, do not merge.

### CODE REVIEW

**Comment by mythi** [comment]
@avalluri baf1c31 and d7f6292 are needed for refkit so I'd propose this PR is rebased and modified to keep those two so that we can prepare for the usrmerge ```DISTRO_FEATURE```.

**Comment by avalluri** [comment]
@mythi    https://github.com/intel/intel-iot-refkit/pull/13/commits/baf1c31184fffc085b1ad7c49912b220b4204ca4 can be dropped as per my new proposed oe-core change (https://github.com/avalluri/openembedded-core/commit/69193edb4a738183df4d4de080629b65c0e5609d) where these links are prepared in image.bbclass.

**Comment by okartau** [comment]
test this please

**Comment by avalluri** [comment]
test this please

**Comment by mythi** [comment]
test this please

**Comment by skuusela** [comment]
I manually tested the image generated by this PR earlier this week and there is a kernel panic with it.

**Comment by avalluri** [comment]
@skuusela  thanks, i will check that.

**Comment by avalluri** [comment]
Yep, i can guess the reason for kernel panic, we should re-introduce baf1c31 , which creates the base links in initramfs image. @skuusela  Thanks again for your efforts

**Comment by mythi** [comment]
@avalluri did you have a change to check the gobject-instrospection-data with Jussi?

**Comment by avalluri** [comment]
Jussi couldn't get time to check this issue, as he was busy with other tasks. I did couple of failed attempts to alter corss.bbclass without DISTRO_FEATURES check.

**Comment by avalluri** [comment]
@Mikko, submitted the patch to oe-core to fix the gobject-introspection-data failure in usrmerge case: https://patchwork.openembedded.org/patch/139629/

**Comment by mythi** [comment]
part of #188

**Pull request closed without merging**
