### PR TITLE
Test Minnowboard Max beignet on YP2.3M3

### PR DESCRIPTION
**Pull request by ipuustin**
Test build (@mythi, @skuusela).

### CODE REVIEW

**Comment by ipuustin** [comment]
This is https://github.com/intel/intel-iot-refkit/pull/65 + a beignet patch.

**Comment by ipuustin** [comment]
test this please

**Comment by ipuustin** [comment]
test this please

**Comment by ipuustin** [comment]
test this please

**Comment by ipuustin** [comment]
test this please

**Comment by ipuustin** [comment]
test this please

**Comment by ipuustin** [comment]
test this please

**Comment by ipuustin** [comment]
test this please

**Comment by ipuustin** [comment]
I flashed the same image which fails testing, and locally the test passes fine. It could be that something goes wrong with the test setup? The test takes the same time when run before the `meta-intel` update (42.29 s vs. 42.92 s), so it shouldn't be about that. Thermal issues?

    root@intel-corei7-64:~# time dense_blas-bench-opencl 
    
    ----------------------------------------------
                   Device Info
    ----------------------------------------------
    
    Name:                Intel(R) HD Graphics Bay Trail-T
    Vendor:              Intel
    Type:                GPU 
    Available:           1
    Max Compute Units:   4
    Max Work Group Size: 256
    Global Mem Size:     990904320
    Local Mem Size:      65536
    Local Mem Type:      1
    Host Unified Memory: 1
    
    
    Benchmark : BLAS
    ----------------
    sCOPY : 2.68 GB/s
    sAXPY : 2.67 GB/s
    sDOT : 3.29 GB/s
    sGEMV-N : 1.45 GB/s
    sGEMV-T : 1.47 GB/s
    sGEMM-NN : 4.65 GFLOPs/s
    sGEMM-NT : 4.9 GFLOPs/s
    sGEMM-TN : 4.04 GFLOPs/s
    sGEMM-TT : 4.5 GFLOPs/s
    ----
    real    0m 42.29s
    user    0m 10.78s
    sys     0m 0.86s
    root@intel-corei7-64:~# uname -a
    Linux intel-corei7-64 4.9.12-yocto-standard #1 SMP PREEMPT Mon Mar 13 10:46:29 UTC 2017 x86_64 GNU/Linux
    root@intel-corei7-64:~# cat /etc/os-release 
    ID="refkit"
    NAME="IoT Reference OS Kit for Intel(r) Architecture"
    VERSION="1.0+snapshot-20170315"
    VERSION_ID="1.0+snapshot-20170315"
    PRETTY_NAME="IoT Reference OS Kit for Intel(r) Architecture 1.0+snapshot-20170315"
    BUILD_ID="2017-03-15_05-39-17-build-413"

**Comment by ipuustin** [comment]
After updating MinnowBoard BIOS from 90 to 94, the same image crashes:

    root@intel-corei7-64:~# dense_blas-bench-opencl 
    
    ----------------------------------------------
                   Device Info
    ----------------------------------------------
    
    [   30.542795] BUG: unable to handle kernel paging request at 0000000fffffffe8
    [   30.550958] IP: [<ffffffff8158bcec>] i915_vma_unbind+0xac/0x310
    [   30.557860] PGD 0 [   30.559998] 
    [   30.561758] Oops: 0002 [#1] PREEMPT SMP
    [   30.566209] Modules linked in: xt_connmark iptable_nat nf_nat_ipv4 nf_nat iptable_mangle snd_hda_codec_hdmi snd_hda_intel snd_hda_codec snd_intel_sst_acpi intel_rapl snd_hda_core snd_intel_sst_core intel_soc_dts_iosf intel_powerclamp coretemp efivars snd_soc_sst_mfld_platform snd_soc_sst_match snd_soc_rt5645 snd_soc_rt5640 mei_txe mei snd_soc_rl6231 snd_soc_core snd_compress ac97_bus snd_pcm snd_timer dw_dmac i2c_designware_platform pwm_lpss_platform i2c_designware_core pwm_lpss spi_pxa2xx_platform nf_conntrack_ipv4 nf_defrag_ipv4 nf_conntrack_ipv6 nf_defrag_ipv6 uio xt_tcpudp ip6table_filter iwlwifi cfg80211 xt_conntrack ip6_tables nf_conntrack iptable_filter ip_tables x_tables
    [   30.636894] CPU: 0 PID: 563 Comm: dense_blas-benc Not tainted 4.9.12-yocto-standard #1
    [   30.646065] Hardware name: ADI Minnowboard Turbot D0 PLATFORM/MinnowBoard Turbot, BIOS MNW2MAX1.X64.0094.R01.1612052239 12/05/2016
    [   30.659661] task: ffff8800723c0b00 task.stack: ffffc90001408000
    [   30.666522] RIP: 0010:[<ffffffff8158bcec>]  [<ffffffff8158bcec>] i915_vma_unbind+0xac/0x310
    [   30.676227] RSP: 0018:ffffc9000140ba98  EFLAGS: 00010282
    [   30.682384] RAX: ffff880075651368 RBX: 0000000000000000 RCX: ffff880075453b90
    [   30.690650] RDX: ffff880075453b98 RSI: 0000000fffffffe0 RDI: ffff880075690020
    [   30.698917] RBP: ffffc9000140bad8 R08: 0000000000000000 R09: ffff8800754535f8
    [   30.707181] R10: ffffc9000140bbd0 R11: ffff880075453a20 R12: ffff8800798ee000
    [   30.715448] R13: 0000000000000000 R14: 0000000000000a84 R15: ffff880075453a00
    [   30.723718] FS:  00007f3da5dfa740(0000) GS:ffff880078000000(0000) knlGS:0000000000000000
    [   30.733087] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
    [   30.739748] CR2: 0000000fffffffe8 CR3: 0000000072384000 CR4: 00000000001006f0
    [   30.748014] Stack:
    [   30.750350]  ffff88007541f110 ffffffff813fe14f ffffc9000140baf8 ffff880075443a00
    [   30.759012]  ffff8800798ee000 ffff880077fb5340 0000000000000a84 ffff8800798ee000
    [   30.767672]  ffffc9000140baf8 ffffffff8156d962 0000000000010000 000000007fff0000
    [   30.776329] Call Trace:
    [   30.779183]  [<ffffffff813fe14f>] ? radix_tree_node_alloc+0x4f/0x90
    [   30.786458]  [<ffffffff8156d962>] i915_gem_evict_for_vma+0x52/0xb0
    [   30.793629]  [<ffffffff8158bb11>] __i915_vma_do_pin+0x3e1/0x450
    [   30.800502]  [<ffffffff810ba3d6>] ? cpuacct_charge+0x86/0xa0
    [   30.807063]  [<ffffffff8156dce4>] i915_gem_execbuffer_reserve_vma.isra.29+0x144/0x1b0
    [   30.816145]  [<ffffffff8156e0d0>] i915_gem_execbuffer_reserve.isra.30+0x380/0x3a0
    [   30.824829]  [<ffffffff8156f6b8>] i915_gem_do_execbuffer.isra.36+0x618/0x17c0
    [   30.833104]  [<ffffffff810a024e>] ? finish_task_switch+0x8e/0x1c0
    [   30.840174]  [<ffffffff8199240e>] ? __schedule+0x17e/0x5a0
    [   30.846542]  [<ffffffff81997dfb>] ? retint_kernel+0x1b/0x1d
    [   30.863189]  [<ffffffff81570be5>] i915_gem_execbuffer2+0xa5/0x220
    [   30.880303]  [<ffffffff8151dcda>] drm_ioctl+0x1ea/0x460
    [   30.896326]  [<ffffffff81570b40>] ? i915_gem_execbuffer+0x2e0/0x2e0
    [   30.913558]  [<ffffffff8117b092>] ? handle_mm_fault+0x4b2/0xe20
    [   30.930357]  [<ffffffff8119c2eb>] ? kmem_cache_alloc+0x19b/0x1b0
    [   30.947225]  [<ffffffff8119c2eb>] ? kmem_cache_alloc+0x19b/0x1b0
    [   30.964001]  [<ffffffff811c09f4>] do_vfs_ioctl+0x94/0x5c0
    [   30.980123]  [<ffffffff8104a6e7>] ? __do_page_fault+0x277/0x4e0
    [   30.996875]  [<ffffffff811c0f99>] SyS_ioctl+0x79/0x90
    [   31.012437]  [<ffffffff81997460>] entry_SYSCALL_64_fastpath+0x13/0x94
    [   31.029450] Code: 3f ff ff ff 4c 89 ff e8 b3 8a f9 ff 49 8b 47 70 49 8d 8f 90 01 00 00 49 8b 97 98 01 00 00 49 8b b7 90 01 00 00 48 05 58 03 00 00 <48> 89 56 08 48 89 32 48 8b 50 08 48 89 48 08 49 89 87 90 01 00
    [   31.072507] RIP  [<ffffffff8158bcec>] i915_vma_unbind+0xac/0x310
    [   31.089336]  RSP <ffffc9000140ba98>
    [   31.102993] CR2: 0000000fffffffe8
    [   31.116502] ---[ end trace e8a12d8848ce3a0c ]---

**Comment by ipuustin** [comment]
Bug reported here: https://bugs.freedesktop.org/show_bug.cgi?id=100229

**Comment by ipuustin** [comment]
test this please

**Comment by ipuustin** [comment]
retest this please

**Comment by mythi** [comment]
obsolete

**Pull request closed without merging**
