### PR TITLE
oeqa/runtime: Restructuring runtime test suite

### PR DESCRIPTION
**Pull request by pacopedraza**
Reestructuration of all the test suite for runtime
Created the following directories:
bsp, conformance, connectivity, core, multimedia, peripherals, programming

Signed-off-by: Francisco Pedraza <francisco.j.pedraza.gonzalez@intel.com>

### CODE REVIEW

**Comment by mythi** [comment]
@skuusela needs daft changes too?

**Comment by skuusela** [comment]
@mythi @pacopedraza Docker/tester-exec.sh needs a change:
```
# Copy local WLAN settings to iottest over example file and chmod to readable
_WLANCONF=./iottest/oeqa/runtime/sanity/files/config.ini
cp $HOME/.config.ini.wlan ${_WLANCONF}
```
`_WLANCONF` should be changed to `./iottest/oeqa/runtime/connectivity/wifi/files/config.ini`

**Comment by mythi** [comment]
@pacopedraza I will not merge this until CI shows green. Please update the PR with changes suggested by @skuusela

**Comment by pacopedraza** [comment]
Hi @mythi @ibarraJhumberto is working on it, he will push the fix today.

**Comment by pacopedraza** [comment]
I merged Humberto's patch for fixing issue with "Docker/tester-exec.sh"

**Comment by mythi** [comment]
Test this please

**Comment by ibarraJhumberto** [comment]
Checking. It would help if the details showed a complete log though, is there a way to know what failed? Or to know exactly what is run with CI? Is it a specific manifest or a specific version of a manifest being run?

**Comment by skuusela** [comment]
@ibarraJhumberto There was some problem with the CI and thats why this failed. It has been solved now. test this please

**Comment by pacopedraza** [comment]
Rebased to master d4f8ab4202d8f55a39364fb24d381e66b8b8dab7

**Comment by mythi** [comment]
@pacopedraza I just realized this isn't right. You can do ```git mv``` to move files around. No need for 'add copies' and 'remove old' commits separately.

**Comment by mythi** [comment]
obsolete

**Pull request closed without merging**
