### PR TITLE
refkit: upstream component update

### PR DESCRIPTION
**Pull request by pohly**
Updating as many components as possible...

### CODE REVIEW

**Comment by rojkov** [comment]
Looks good to me

**Comment by pohly** [comment]
The new bitbake apparently isn't quite as reliable as it needs to be (https://intel-iot-refkit.01.org/job/intel-iot-refkit_pull-requests/82/console):

```
03:09:41.363 [post-build-test]   File "/srv/jenkins/workspace/ci-2017-07-24_04-48-12-build-82/openembedded-core/meta/lib/oeqa/core/case.py", line 41, in _oeSetUp
03:09:41.363 [post-build-test]     self.setUpMethod()
03:09:41.363 [post-build-test]   File "/srv/jenkins/workspace/ci-2017-07-24_04-48-12-build-82/openembedded-core/meta/lib/oeqa/selftest/case.py", line 150, in setUp
03:09:41.363 [post-build-test]     self.setUpLocal()
03:09:41.363 [post-build-test]   File "/srv/jenkins/workspace/ci-2017-07-24_04-48-12-build-82/meta-refkit/lib/oeqa/selftest/cases/refkit_poky.py", line 172, in setUpLocal
03:09:41.363 [post-build-test]     shutil.rmtree(self.poky_dir)
03:09:41.363 [post-build-test]   File "/usr/lib64/python3.4/shutil.py", line 468, in rmtree
03:09:41.363 [post-build-test]     _rmtree_safe_fd(fd, path, onerror)
03:09:41.363 [post-build-test]   File "/usr/lib64/python3.4/shutil.py", line 426, in _rmtree_safe_fd
03:09:41.363 [post-build-test]     onerror(os.unlink, fullname, sys.exc_info())
03:09:41.363 [post-build-test]   File "/usr/lib64/python3.4/shutil.py", line 424, in _rmtree_safe_fd
03:09:41.363 [post-build-test]     os.unlink(name, dir_fd=topfd)
03:09:41.363 [post-build-test] FileNotFoundError: [Errno 2] No such file or directory: 'bitbake.sock'
```

New commits in bitbake might help.

**Comment by pohly** [comment]
test this please

Intermittent proxy failure.

**Comment by pohly** [comment]
@rojkov can you have another look? I added some more changes.

Commit 1f85d61 has been part of multiple successful builds now, so it seems that explicitly asking the bitbake server to shut down works well enough.

**Comment by rojkov** [comment]
Looks good to me

**Pull request merged**
