### PR TITLE
TEST: build on Ubuntu

### PR DESCRIPTION
**Pull request by pohly**
Same as PR #220, just with less work to be done and extra debug output.

### CODE REVIEW

**Comment by pohly** [comment]
Test this please.

**Comment by pohly** [comment]
test this please

**Comment by pohly** [comment]
Rebased and using a bitbake where the "bad file descriptor" error has special error handling.

**Comment by okartau** [comment]
the 2nd commit of those you picked from PR#220 that adds packages, was updated in PR#220, this is needed to get xml reporting to work (the thing where pip needs to be used)

**Comment by pohly** [comment]
We understand the root cause of the problem on Ubuntu (no_proxy=.<some domain> had no effect, see https://bugs.python.org/issue29142), so this PR can be closed.

**Pull request closed without merging**
