### PR TITLE
fix eSDK configuration

### PR DESCRIPTION
**Pull request by mythi**
Signed-off-by: Mikko Ylinen <mikko.ylinen@linux.intel.com>

### CODE REVIEW

**Comment by gvancuts** [comment]
With this change, are we testing building a full or minimal eSDK (or both)?

**Comment by mythi** [comment]
@gvancuts this PR tests full only.

**Comment by gvancuts** [comment]
Thanks @mythi. I think there is value in testing both over time but this is definitely a very good step forward! 👍

**Comment by mythi** [comment]
test this please

**Comment by uhofemei** [comment]
@mythi I can't seem to build from your tree. 

++ . /data/intel-iot-refkit/openembedded-core/scripts/oe-buildenv-internal
refkit-init-build-env: line 62: /data/intel-iot-refkit/openembedded-core/scripts/oe-buildenv-internal: No such file or directory
++ unset OEROOT
++ return 1

**Comment by uhofemei** [comment]
Populating the extensible SDK will fail using this PR.

```Gathering file list
Processing files
Processing /data/intel-iot-refkit/build/bb-cache/sstate/universal-4.8/bd/sstate:libpng-native:x86_64-linux:1.6.28:r0:x86_64:3:bd66f45d1a5d7bf217d97194d1d2d916_populate_sysroot.tgz... linking
Traceback (most recent call last):
  File "/data/intel-iot-refkit/openembedded-core/scripts/gen-lockedsig-cache", line 65, in <module>
    os.link(src, dst)
OSError: [Errno 18] Invalid cross-device link: '/data/intel-iot-refkit/build/bb-cache/sstate/universal-4.8/bd/sstate:libpng-native:x86_64-linux:1.6.28:r0:x86_64:3:bd66f45d1a5d7bf217d97194d1d2d916_populate_sysroot.tgz' -> '/data/intel-iot-refkit/build/tmp-glibc/work/intel_corei7_64-refkit-linux/refkit-image-gateway/1.0-r0/sdk-ext/image//usr/local/refkit-x86_64/sstate-cache/universal-4.8/bd/sstate:libpng-native:x86_64-linux:1.6.28:r0:x86_64:3:bd66f45d1a5d7bf217d97194d1d2d916_populate_sysroot.tgz'


ERROR: refkit-image-gateway-1.0-r0 do_populate_sdk_ext: Function failed: copy_buildsystem
ERROR: Logfile of failure stored in: /data/intel-iot-refkit/build/tmp-glibc/work/intel_corei7_64-refkit-linux/refkit-image-gateway/1.0-r0/temp/log.do_populate_sdk_ext.4524
ERROR: Task (/data/intel-iot-refkit/openembedded-core/../meta-refkit/recipes-image/images/refkit-image-gateway.bb:do_populate_sdk_ext) failed with exit code '1'```

This is because OE core needs to be rebased to include this patch:
http://cgit.openembedded.org/openembedded-core/commit/?id=403dd205828002d6ef4e8b474aedb6082289e22f

**Comment by uhofemei** [comment]
Applying the patch it fails at a different package with the same error message. 

```Processing /data/intel-iot-refkit/build/bb-cache/sstate/universal-4.8/95/sstate:util-macros-native:x86_64-linux:1.19.1:r0:x86_64:3:9528d8c99a296b49bc85d7da54204b47_populate_sysroot.tgz.siginfo... linking
Traceback (most recent call last):
  File "/data/intel-iot-refkit/openembedded-core/scripts/gen-lockedsig-cache", line 65, in <module>
    os.link(src, dst)
OSError: [Errno 18] Invalid cross-device link: '/data/intel-iot-refkit/build/bb-cache/sstate/universal-4.8/95/sstate:util-macros-native:x86_64-linux:1.19.1:r0:x86_64:3:9528d8c99a296b49bc85d7da54204b47_populate_sysroot.tgz.siginfo' -> '/data/intel-iot-refkit/build/tmp-glibc/work/intel_corei7_64-refkit-linux/refkit-image-gateway/1.0-r0/sdk-ext/image//usr/local/refkit-x86_64/sstate-cache/universal-4.8/95/sstate:util-macros-native:x86_64-linux:1.19.1:r0:x86_64:3:9528d8c99a296b49bc85d7da54204b47_populate_sysroot.tgz.siginfo'
```

**Comment by gvancuts** [comment]
What kind of partition (filesystem and mount options) are you using to build the IoT RefKit on your dev machine?

**Comment by uhofemei** [comment]
The oe-core submodule in Mikko's tree needed updating. I pulled his latest commit that fixes this and am rebuilding.

**Comment by uhofemei** [comment]
@mythi with OE-core rebased it still fails. The patch Paul pointed to in email is what's needed. Here: http://cgit.openembedded.org/openembedded-core/commit/?id=fb9fdd7a74917cdcab039aa3a9a9944b18246fea

**Comment by mythi** [comment]
@uhofemei AFAICT that is included. See the commit message for e4ed040

**Comment by uhofemei** [comment]
@mythi it was not. I had to patch the file.

**Comment by mythi** [comment]
@uhofemei sounds like you did not run ```git submodule update openembedded-core```

**Comment by uhofemei** [comment]
@mythi that's what it was. All good now 👍

**Comment by mythi** [comment]
test this please

**Comment by mythi** [comment]
test this please

**Pull request merged**
