### PR TITLE
[TEST-dont-merge] Trials with new CI, not for real changes

### PR DESCRIPTION
**Pull request by okartau**
test & debug new refkit own  CI

Signed-off-by: Olev Kartau <olev.kartau@intel.com>

### CODE REVIEW

**Comment by okartau** [comment]
tezt this

**Comment by okartau** [comment]
tezt this

**Comment by okartau** [comment]
tezt this

**Comment by okartau** [comment]
test this please

**Comment by mythi** [comment]
closing temporarily, please reopen later

**Pull request closed without merging**
