### PR TITLE
OpenCV DNN module and test

### PR DESCRIPTION
**Pull request by ipuustin**
OpenCV DNN module, update of meta-openembedded (to fix compilation issues), and a test for DNN.

### CODE REVIEW

**Comment by ipuustin** [comment]
This replaces #186. I didn't want to force push to the branch because it's not clear to me if #186 is eventually contained in #190 or not.

**Comment by mythi** [comment]
On Thu, Jun 15, 2017 at 9:26 PM, Ismo Puustinen wrote:

> This replaces #186 <https://github.com/intel/intel-iot-refkit/pull/186>.
> I didn't want to force push to the branch because it's not clear to me if
> #186 <https://github.com/intel/intel-iot-refkit/pull/186> is eventually
> contained in #190 <https://github.com/intel/intel-iot-refkit/pull/190> or
> not.
>
>
> I dropped #186 because it *looks* it makes the installer test to fail. No
solid data though. Let's see.

**Comment by ipuustin** [comment]
retest this please

**Comment by mythi** [comment]
@ipuustin did this pass CI testing earlier? PR #209 fails with the same error as the latest build for this PR

**Comment by okartau** [comment]
(order from latest to older, as reported in github-pullrequest/ sub-page of job:
This PR test has been OK once and failed all other times.
Seems that most of revocations have been via "start all" glitch.

failed in #1680 #1661 #1642 
OK in #1629 
failed in #1616 #1609 #1526 #1519 #1518

**Comment by ipuustin** [comment]
The bug looks like there is no dependency from meta-iotqa to meta-ros. I wonder how it passed testing when originally merged though (the master build + tests are good).

**Comment by mythi** [comment]
On Tue, Jun 27, 2017 at 12:57 PM, Ismo Puustinen <notifications@github.com>
wrote:

> The bug looks like there is no dependency from meta-iotqa to meta-ros. I
> wonder how it passed testing when originally merged though (the master
> build + tests are good).
>
>
>
AFAICS no testing covers that dependency checking. It only triggers when
you set computervision profile to depend on iotqa. computervision layer
compatibility is checked.

**Comment by ipuustin** [comment]
@mythi : Ok, I tried to break the dependency between meta-refkit-computervision and meta-iotqa by moving computer vision test packages into meta-refkit-computervision.

**Pull request merged**
