### PR TITLE
Pull in the latest changes from meta-iot-web

### PR DESCRIPTION
**Pull request by nagineni**
Pull in the latest changes from meta-iot-web. Also, re-name restful user home directory. 

Signed-off-by: Sudarsana Nagineni sudarsana.nagineni@intel.com

### CODE REVIEW

**Comment by poussa** [comment]
LGTM.

@mythi ?

**Comment by okartau** [comment]
test this please

**Comment by okartau** [comment]
test this please

**Comment by mythi** [comment]
test this please

**Comment by poussa** [comment]
The image is quite impossible to use or test on MinnowBoard Turbot since the serial console does not work. One need HDMI display and keyboard to test anything. The serial console need to be fixed asap.

**Comment by mythi** [comment]
On Tue, Feb 7, 2017 at 12:45 PM, Sakari Poussa wrote:

> The image is quite impossible to use or test on MinnowBoard Turbot since
> the serial console does not work. One need HDMI display and keyboard to
> test anything. The serial console need to be fixed asap.
>

I'm going to submit a fix for that today.

**Comment by mythi** [comment]
See #6

**Comment by nagineni** [comment]
> See #6

@mythi thanks! I will try it.

Can you merge this PR if it is okay to go in?

**Comment by mythi** [comment]
I'm going to merge it if it works as expected and I get a +1

**Comment by nagineni** [comment]
I already tested on MinnowBoard and changes are working fine.

**Comment by poussa** [comment]
+1 

I have tested it and works as expected. Also others have done testing reporting no issues.

@mythi please merge since stakeholders demands the features of this PR.

**Comment by nagineni** [comment]
Rebased on master.

**Pull request merged**
