### PR TITLE
Remove gtk dependency from opencv

### PR DESCRIPTION
**Pull request by juimonen**
Signed-off-by: Jaska Uimonen <jaska.uimonen@intel.com>

### CODE REVIEW

**Comment by ipuustin** [comment]
Previous additions to OpenCV `PACKAGECONFIG` are here: https://github.com/intel/intel-iot-refkit/blob/master/meta-refkit-core/conf/distro/include/refkit-config.inc#L147

**Comment by juimonen** [comment]
so whats the logic of putting certain things there and certain things here (as bbappends)?

**Comment by jlaako** [comment]
Having PACKAGECONFIG_remove_pn-opencv_df-refkit-config = "gtk" in refkit-config.inc works

**Comment by juimonen** [comment]
ok, this new version should work, although not sure about the correct place of the fix...

**Comment by mythi** [comment]
My preference is to keep all ```PACKAGECONFIG``` changes in one place (in our case refkit-config.in) for the sake of clarity and readability.

**Comment by juimonen** [comment]
ok, moved to refkit-config.inc

**Comment by mythi** [comment]
@juimonen the change looks good to me but the commit message is missing the *why* part. is it pulling something we don't want?

**Comment by jlaako** [comment]
gtk-3 pulls in lot of dependencies, so we may want to be careful when/if we want to pull it in

**Pull request merged**
