### PR TITLE
Update meta-security-isafw to remove cve-check-tool recipe.

### PR DESCRIPTION
**Pull request by ipuustin**
There appears to be an issue with cve-check-tool from meta-security-isafw. See if oe-core version of the tool works better.

### CODE REVIEW

**Comment by ipuustin** [comment]
An alternative to this patch should be merging https://github.com/01org/meta-security-isafw/pull/84 and then updating the layer.

**Comment by ipuustin** [comment]
It seems that `isafw.bbclass` keeps working after this change. Also the cve check tool results are available again.

**Comment by mythi** [comment]
@ipuustin thanks!

**Comment by ipuustin** [comment]
Rebased.

**Pull request merged**
