### PR TITLE
RMC hardening + NUC boot fixes

### PR DESCRIPTION
**Pull request by mythi**

### CODE REVIEW

**Comment by mythi** [comment]
@pohly FYI

**Comment by pohly** [comment]
Where is the code which used to read the RMC DB from the VFAT system partition? Is that now gone for sure?

**Comment by mythi** [comment]
@pohly That's in ```SRC_URI_remove_intel-x86-common = "file://0004-sd-boot-Support-global-kernel-command-line-fragment-in-EFI-stub.patch"```

**Comment by pohly** [comment]
On Tue, 2017-02-28 at 00:03 -0800, Mikko Ylinen wrote:
> @pohly That's in SRC_URI_remove_intel-x86-common =
> "file://0004-sd-boot-Support-global-kernel-command-line-fragment-in-EFI-stub.patch"

I hadn't considered that meta-intel carries that patch. This
SRC_URI_remove is a bit fragile - consider what happens when the patch
gets renamed (for whatever reason) in meta-intel...

I'm also a bit concerned that we now have systemd-boot patches in both
meta-intel and meta-refkit. I understand that this is necessary because
the UEFI app currently is a refkit-only thing. Perhaps now would be a
good opportunity to move it to meta-intel, together with these
enhancements?

**Comment by mythi** [comment]
@pohly this is just a test-build. I'm going to drop fc6803a once meta-intel has those patches. They are already submitted there.

**Comment by pohly** [comment]
On Tue, 2017-02-28 at 02:36 -0800, Mikko Ylinen wrote:
> @pohly this is just a test-build. I'm going to drop fc6803a once
> meta-intel has those patches. They are already submitted there.

Makes sense. That it's just a test build wasn't clear.

**Comment by mythi** [comment]
not serving a purpose now

**Pull request closed without merging**
