### PR TITLE
[TEST BUILD] ostree-upgradable image support

### PR DESCRIPTION
**Pull request by klihub**
Try to test-build in the CI infra to see the amount of damage we've managed to inflict...

### CODE REVIEW

**Comment by okartau** [comment]
test this please

**Comment by okartau** [comment]
test this please

**Comment by klihub** [comment]
The tests got stuck because the swtpm test script could not find netstat, which it fails to check and detect, in which case (if the swtpm process the script would like to connect to keeps running) the script essentially falls into an infinite loop.

The immediate reason why netstat was not found is that it was not on the PATH of the test script. My current guess is that the reason for this is related to the usrmerge patches: the script has the same (recipe-sysroot-native)/usr/bin and (recipe-sysroot-native)/usr/sbin twice on its PATH which looks suspicious, while at the same time the native recipes ignore usrmerge and install stuff in a split /-/usr fashion.

So I suspect that usrmerge somehow gets propagated to the paths which effect how the tests are run, in practice dropping /bin and /sbin from the PATH, while the actual installation happens ignoring usrmerge exactly to these dropped locations. Sigh...

Ditto for flatpak build.

**Comment by klihub** [comment]
Let's see if a quick workaround gets rid of this problem...

**Comment by klihub** [comment]
Well, I guess I can call it a day, then...

**Comment by avalluri** [comment]
@klihub renaming the 'swtpm-wrappers.bb' recipe to 'swtpm-wrappers-native.bb'(and related changes in refkit.conf, refkit-ci.inc, image-installer.py, init-tpm, runqemu-installer, and runqeum-insternal-disk)  fixes the issue. I think bitbake's convention is that all native recipes should be suffixed with '-native', then its is treating differently.

**Comment by pohly** [comment]
On Sun, 2017-04-23 at 15:01 -0700, Amarnath Valluri wrote:
> @klihub renaming the 'swtpm-wrappers.bb' recipe to
> 'swtpm-wrappers-native.bb'(and related changes in refkit.conf,
> refkit-ci.inc, image-installer.py, init-tpm, runqemu-installer, and
> runqeum-insternal-disk) fixes the issue. I think bitbake's convention
> is that all native recipes should be suffixed with '-native', then its
> is treating differently.

There's an "inherit native" in swtpm-wrappers.bb. If that's not enough,
then the class should enforce that convention or at least warn about it.

Sounds like this needs to be brought up on the OE-core mailing list. Has
that been done while I was on vacation?

**Comment by avalluri** [comment]
@pohly, I realized this yesterday, so I did not bring this yet to oe-core list.

**Comment by mythi** [comment]
replaced by #208

**Pull request closed without merging**
