### PR TITLE
image: adjust partition sizes

### PR DESCRIPTION
**Pull request by pohly**
They were inconsistent and too small for future use cases.

Replaces PR #36 and needed for PR #19, which already had commit
13829d8.

### CODE REVIEW

**Comment by mythi** [comment]
@pohly are the submodule updates necessary?

**Comment by pohly** [comment]
On Thu, 2017-02-23 at 07:28 -0800, Mikko Ylinen wrote:
> @pohly are the submodule updates necessary?

No, that crept in unintentionally (juggling between my image-installer
branch and this PR). I'll amend it.

**Comment by pohly** [comment]
Force-pushed updated commit.

**Comment by mythi** [comment]
test this please

**Comment by ipuustin** [comment]
@pohly I also keep committing the submodules unintentionally (`git commit .` is the main cause). I was thinking of a commit hook to warn about it, but I don't know if that would interfere too much with the legitimate submodule updates.

**Comment by pohly** [comment]
@ipuustin if the change for the submodule was a bit more obvious in "git diff" output perhaps it would be easier to spot the mistake - at least I tend to check my change that way before committing. But I've not found a way to get more than the two-line change with old and new hash, which is just too easy to miss.

**Comment by mythi** [comment]
+1

@jlaako Are you OK?

**Comment by jlaako** [comment]
@mythi yes, +1

**Pull request merged**
